# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def shared_pods
    pod 'Alamofire'
    pod 'AlamofireImage'
end

target 'ModernFertility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ModernFertility
  shared_pods
end

target 'ModernFertilityTests' do
  inherit! :search_paths
  # Pods for testing
  shared_pods
  pod 'OHHTTPStubs/Swift'
end

target 'ModernFertilityUITests' do
  # Pods for testing
end

post_install do |installer|

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end

end